#!/usr/bin/env bash
# Write one example ledger per multi-currency scenario, with the statement it
# produces, into examples/multi-currency/.
#
# These are not test fixtures. Nothing asserts against them: they exist so a
# reader of docs/multi-currency.md can import one and get the same page the doc
# shows, rather than taking its word for it. They are generated from the
# fixtures in tests/fixtures/ and from what the tool actually prints, so
# regenerating them after a change is how they stay true.
#
#     ./scripts/generate-multi-currency-examples.sh            # in Docker
#     ./scripts/generate-multi-currency-examples.sh --here     # already inside
#
# Each file is the book exported whole — accounts, transactions and prices — so
# it re-imports into an empty book and draws the same statement with no rates
# file. That is the property that makes it checkable:
#
#     gnucash-plaintext import --new /tmp/check.gnucash <the example>
#     gnucash-plaintext balance-sheet /tmp/check.gnucash --as-of <the date>
#
# An export states `share_price:` as the value over the amount, which is the
# rate the two figures actually make. A ledger written by hand may state it to
# more places than the rounded value supports, and the import then says so and
# uses the amounts' — which is why these carry the export's form.
#
# **The `guid:` lines are load-bearing — do not strip them to tidy the files.**
# A disposal refers to the purchase it draws on by guid, in
# `cost_basis_split_guid:`. Remove the guids and that reference matches
# nothing, so the sale draws on no cost basis: measured on the buy-and-sell
# example, a guid-free copy imported at exit 0, said only
# `cost_basis_split_guid '...' matches no split in the book`, and drew a page
# reading 0.00 realized and 150.00 unrealized where the real book says 100.00
# and 0.00. Wrong, and quietly.
set -euo pipefail

TAG="${TAG:-latest}"
OUT="examples/multi-currency"
F="tests/fixtures"

if [ "${1:-}" != "--here" ]; then
    exec docker run --rm -v "$PWD:/workspace" --user "$(id -u):$(id -g)" \
        -e TAG="$TAG" -e REGENERATE="${REGENERATE:-}" "gnucash-dev:$TAG" bash -c \
        'set -e
         export HOME=/tmp/home PYTHONDONTWRITEBYTECODE=1
         mkdir -p $HOME
         cd /workspace
         python3 -m pip install -e ".[dev]" --break-system-packages --user -q 2>&1 | tail -1
         export PATH=$HOME/.local/bin:$PATH
         ./scripts/generate-multi-currency-examples.sh --here'
fi

BOOKS="$(mktemp -d)"
trap 'rm -rf "$BOOKS"' EXIT
mkdir -p "$OUT"

gp() { python3 -m cli.main "$@"; }

# GnuCash refuses a second save in the same second, so the backup a save would
# collide with is removed between steps, the way tests/conftest.py does it.
settle() { rm -f "$1".2* ; }

# The year-end price the reported example's rates file supplies, written into
# the book so the ledger prices itself and needs no --fx-rates.
year_end_price() {
    printf '%s\n' 'price' \
        '	commodity.namespace: "CURRENCY"' \
        '	commodity.mnemonic: "USD"' \
        '	currency.mnemonic: "CAD"' \
        '	time: "2026-12-31 12:00:00 +0000"' \
        '	value: "2773/2000"' \
        '	source: "user:price-editor"' \
        '	type: "last"' > "$BOOKS/year-end.txt"
}

# $1 book  $2 as-of  $3 file  $4 title  $5.. description lines
#
# Where the example already exists, its own ledger is what the book is rebuilt
# from, not the fixtures — so the guids stay as they were and a regeneration
# changes nothing unless a figure has. An export carries a guid for every
# account, transaction, split and price, and a fresh import mints new ones, so
# building from the fixtures every time rewrote every file on every run and
# no reader could tell a real change from the noise. Measured: importing an
# example as it stands and exporting it again writes the identical ledger.
#
# REGENERATE=fixtures rebuilds from tests/fixtures/ instead, which is what to
# use when a fixture or a figure has actually changed.
write_example() {
    local book="$1" as_of="$2" file="$3" title="$4"; shift 4
    local path="$OUT/$file"

    if [ -f "$path" ] && [ "${REGENERATE:-}" != fixtures ]; then
        sed '/^# ---------------------------------------------------------------$/,$d' \
            "$path" > "$BOOKS/existing.txt"
        local kept="$BOOKS/kept-$file.gnucash"
        rm -f "$kept" "$kept".2*
        if gp import --new "$kept" "$BOOKS/existing.txt" \
               --include-business-objects > /dev/null 2>&1; then
            rm -f "$kept".2*
            book="$kept"
        fi
    fi
    {
        echo "# $title"
        echo "#"
        for line in "$@"; do echo "# $line"; done
        echo "#"
        echo "# Generated by scripts/generate-multi-currency-examples.sh. Not a"
        echo "# test fixture — no test draws its figures from here — but the"
        echo "# statement below is checked against what the tool prints, by"
        echo "# tests/integration/test_each_worked_example_still_prints_the_statement_it_carries.py."
        echo "# Check it yourself:"
        echo "#"
        echo "#     gnucash-plaintext import --new /tmp/check.gnucash \\"
        echo "#         examples/multi-currency/$file"
        echo "#     gnucash-plaintext balance-sheet /tmp/check.gnucash --as-of $as_of"
        echo "#"
        echo "# The statement that ledger produces is at the end of this file."
        echo
    } > "$path"
    # Business objects as well as prices: the invoice scenarios are about a
    # customer being invoiced, and a file holding the posting transaction while
    # omitting the invoice and the customer is a poor example of that. It is
    # also what made those three churn — a ledger that states an `owner:` no
    # block in it declares does not re-import, so they were rebuilt from the
    # fixtures on every run and took fresh guids each time.
    gp export "$book" -o "$BOOKS/led.txt" \
        --include-prices --include-business-objects > /dev/null 2>&1
    cat "$BOOKS/led.txt" >> "$path"
    {
        echo
        echo "# ---------------------------------------------------------------"
        echo "# What \`balance-sheet --as-of $as_of\` prints for the book above."
        echo "#"
        echo "# Commented, every line of it. A statement opens with a dated"
        echo "# directive — \`$as_of balance-sheet\` — and the import reads a"
        echo "# line at column 0 as one, so a file carrying both would refuse to"
        echo "# import and this example would not do the one thing it is for."
        echo "# ---------------------------------------------------------------"
        echo
    } >> "$path"
    gp balance-sheet "$book" --as-of "$as_of" | sed 's/^/# /' >> "$path"

    # The file has to do what its own header tells a reader to do. A generator
    # that can write one which does not is worth no more than the claim it
    # makes, so this checks rather than trusts.
    local proof="$BOOKS/proof.gnucash"
    rm -f "$proof" "$proof".2*
    if ! gp import --new "$proof" "$path" > "$BOOKS/proof.log" 2>&1 \
       || grep -qi 'could not be read\|^Error' "$BOOKS/proof.log"; then
        echo "REFUSED: $path does not import — the example would be untrue" >&2
        sed -n '1,12p' "$BOOKS/proof.log" >&2
        exit 1
    fi
    echo "  wrote $path (imports clean)"
}

year_end_price

# --- A Canadian company invoices a US customer, and is later paid ------------
for state in held spent partly; do
    B="$BOOKS/$state.gnucash"
    gp import --new "$B" "$F/a_usd_invoice_collected_into_a_usd_bank.txt" \
        --fx-rates "$F/usd_at_the_invoice_rate_then_lower_at_the_year_end.yaml" \
        --include-business-objects > /dev/null
    settle "$B"
    if [ "$state" != held ]; then
        guid=$(gp fx-balances "$B" | grep 'Accounts Receivable USD' \
               | grep -oE '[0-9a-f]{32}' | head -1)
        src="$F/the_usd_bank_spent_out_against_its_basis.txt"
        [ "$state" = partly ] && src="$F/the_usd_bank_partly_spent_leaving_a_thousand.txt"
        sed "s/{usd_basis}/$guid/" "$src" > "$BOOKS/spend.txt"
        gp import "$B" "$BOOKS/spend.txt" \
            --fx-rates "$F/usd_at_the_invoice_rate_then_lower_at_the_year_end.yaml" > /dev/null
        settle "$B"
    fi
    gp import "$B" "$BOOKS/year-end.txt" > /dev/null
    settle "$B"
done

write_example "$BOOKS/held.gnucash" 2026-12-31 \
    a_us_customer_invoiced_and_the_dollars_still_held.txt \
    "A Canadian company invoices a US customer, and is later paid" \
    "2,720.00 USD billed and collected into a US dollar account. Every" \
    "transaction that brings the dollars in is stated in US dollars, so none" \
    "carries a Canadian figure and GnuCash's own reconstruction has nothing" \
    "to read. At the year end the company still holds all of them." \
    "" \
    "The dollars cost 3,791.14 and are worth 3,771.28, so 19.86 is" \
    "unrealized. Nothing is realized: no dollar has left."

write_example "$BOOKS/spent.gnucash" 2026-12-31 \
    a_us_supplier_paid_out_of_those_dollars.txt \
    "...and then pays a US supplier out of those dollars" \
    "The same company spends all 2,720.00 — a transfer to a payee and two" \
    "bank charges. Each disposal is valued at what those dollars cost, so" \
    "the splits facing it state what they fetched and \$residual\$ takes the" \
    "difference." \
    "" \
    "The 19.86 has moved from unrealized to realized, and nothing is" \
    "unrealized because nothing is held."

write_example "$BOOKS/partly.gnucash" 2026-12-31 \
    some_of_the_dollars_kept_back.txt \
    "...and keeps some of the money back" \
    "The same again, except 1,000.00 USD stays in the account. Both kinds of" \
    "gain are on the page at once: 12.56 realized on what left, 7.30" \
    "unrealized on what is still held." \
    "" \
    "Drawn at another price the realized figure does not move and the" \
    "unrealized one does, which is why they cannot share a line."

# --- Paid several times, several bills paid ---------------------------------
B="$BOOKS/several.gnucash"
gp import --new "$B" "$F/a_cad_book_earning_usd_three_times.txt" > /dev/null
settle "$B"
a=$(gp fx-balances "$B" | grep '^2026-02-01' | grep -oE '[0-9a-f]{32}' | head -1)
b=$(gp fx-balances "$B" | grep '^2026-04-01' | grep -oE '[0-9a-f]{32}' | head -1)
c=$(gp fx-balances "$B" | grep '^2026-06-01' | grep -oE '[0-9a-f]{32}' | head -1)
sed -e "s/{basis_at_130}/$a/g" -e "s/{basis_at_135}/$b/g" -e "s/{basis_at_140}/$c/g" \
    "$F/the_usd_earned_three_times_spent_out_in_four.txt" > "$BOOKS/four.txt"
gp import "$B" "$BOOKS/four.txt" > /dev/null
settle "$B"
write_example "$B" 2026-12-31 \
    paid_in_dollars_three_times_and_three_bills_paid.txt \
    "A company paid in US dollars several times, paying several US bills" \
    "Consulting collected three times — 1,000.00 USD at 1.30, 2,000.00 at" \
    "1.35, 1,000.00 at 1.40 — and four subcontractors paid out of it at" \
    "1.45, 1.50, 1.38 and 1.42." \
    "" \
    "Three cost bases, four disposals, and the first basis is emptied by the" \
    "second payment made against it — so the realized figure has to add up" \
    "across both. It comes to 250.00, and the working lists all four."

# --- Holds US dollars, pays its own bills at home ---------------------------
B="$BOOKS/athome.gnucash"
gp import --new "$B" \
    "$F/a_cad_book_that_bought_usd_at_four_rates_and_spends_only_cad.txt" > /dev/null
settle "$B"
write_example "$B" 2026-12-31 \
    dollars_held_while_the_bills_are_paid_at_home.txt \
    "A company holding US dollars while paying its own bills at home" \
    "1,000.00 USD bought at each of 1.20, 1.30, 1.40 and 1.50 — 5,400.00 for" \
    "4,000.00 dollars — and the rent paid in Canadian dollars throughout." \
    "" \
    "Nothing foreign is ever spent, so nothing is realized, and the holding" \
    "is measured against all four purchases together. The rent moves" \
    "total_assets every time and moves no gain at all."

# --- Bills in US and Hong Kong dollars --------------------------------------
B="$BOOKS/peg.gnucash"
gp import --new "$B" "$F/a_cad_book_earning_cad_usd_and_hkd.txt" > /dev/null
settle "$B"
u=$(gp fx-balances "$B" | grep 'USD Bank' | grep -oE '[0-9a-f]{32}' | head -1)
h=$(gp fx-balances "$B" | grep 'HKD Bank' | grep -oE '[0-9a-f]{32}' | head -1)
sed -e "s/{usd_basis}/$u/g" -e "s/{hkd_basis}/$h/g" \
    "$F/some_of_the_cad_usd_and_hkd_spent.txt" > "$BOOKS/hkd.txt"
gp import "$B" "$BOOKS/hkd.txt" > /dev/null
settle "$B"
write_example "$B" 2026-12-31 \
    billed_in_us_and_hong_kong_dollars.txt \
    "A company billing in both US and Hong Kong dollars" \
    "Invoices in Canadian, US and Hong Kong dollars, with suppliers paid in" \
    "each. The Hong Kong dollar is pegged to the US dollar between 7.75 and" \
    "7.85, so its Canadian rate is the US rate over the peg — exact at each" \
    "end of the band with the US dollar at 1.30: 1/6 at 7.80, 26/155 at" \
    "7.75, 26/157 at 7.85. Those are the prices this book holds." \
    "" \
    "Each currency is measured against its own cost basis and no other. Draw" \
    "the same book as of 2026-11-30 and the peg is 7.85 instead, which turns" \
    "the Hong Kong figure negative while the US dollar stays where it was."

# --- Borrowed US dollars into a Canadian bank -------------------------------
B="$BOOKS/loan.gnucash"
gp import --new "$B" "$F/a_cad_book_that_borrowed_usd_into_its_cad_bank.txt" > /dev/null
settle "$B"
write_example "$B" 2026-01-25 \
    us_dollars_borrowed_into_a_canadian_bank.txt \
    "A Canadian company that borrows US dollars and banks the money at home" \
    "1,000.00 USD borrowed, landing in the Canadian bank as 1,300.00 CAD, so" \
    "the debt is in US dollars while the cash is in Canadian ones. Still" \
    "owed when the sheet is drawn, by which time the dollar is 1.40." \
    "" \
    "The transaction states a Canadian figure for the debt — value:" \
    "-1300.00 on the loan split — and that is what lets a cost basis open on" \
    "it, so what the debt has cost is measured like anything else. The" \
    "figures are negative, because there a cost basis is currency owed" \
    "rather than held. Drawn as of 2026-01-03, the day it was borrowed, both" \
    "keys are 0.00."

# --- Bought and sold every dollar -------------------------------------------
B="$BOOKS/buysell.gnucash"
gp import --new "$B" "$F/a_cad_book_that_bought_a_thousand_usd.txt" > /dev/null
settle "$B"
g=$(gp fx-balances "$B" | grep -oE '[0-9a-f]{32}' | head -1)
sed "s/{usd_basis}/$g/" "$F/the_thousand_usd_sold_at_a_higher_rate.txt" > "$BOOKS/sold.txt"
gp import "$B" "$BOOKS/sold.txt" > /dev/null
settle "$B"
write_example "$B" 2026-12-31 \
    every_dollar_bought_and_sold_again.txt \
    "A company that bought US dollars and sold every one of them" \
    "1,000.00 USD bought at 1.30 and sold at 1.40, with nothing held after." \
    "" \
    "The simplest case there is: 100.00 realized, nothing unrealized. It is" \
    "also the case that shows what GnuCash's own Advanced Portfolio report" \
    "makes of a book this tool writes — Money In equal to Money Out, because" \
    "the disposal is valued at what the dollars cost, so that report sees no" \
    "gain on the disposal and counts the 100.00 as income instead."

# --- Dollars that arrived with no Canadian figure to cost them --------------
B="$BOOKS/drift.gnucash"
gp import --new "$B" \
    "$F/a_cad_book_with_usd_hkd_and_shares_priced_in_its_price_database.txt" > /dev/null
settle "$B"
write_example "$B" 2026-12-31 \
    dollars_that_arrived_with_no_canadian_figure_to_cost_them.txt \
    "A company whose US dollars arrived with no Canadian figure to cost them" \
    "A cost basis records what a currency cost, and only a transaction" \
    "stating a figure in the book's own currency can say. This company" \
    "bought 10,000.00 USD with Canadian dollars, and sold shares for" \
    "2,080.00 USD in a transaction stated in Canadian dollars, so both say" \
    "what they cost. It also borrowed 4,000.00 USD in a transaction written" \
    "wholly in US dollars, which says nothing. Every disposal here states the" \
    "cost basis it came out of, so the cost bases are drawn down as the" \
    "dollars go, and they end holding 3,480.00 USD against the 7,480.00 the" \
    "accounts hold. The 4,000.00 between them is the borrowing." \
    "" \
    "The sheet does not price what is not there. Those dollars keep" \
    "GnuCash's own revaluation instead, and say so with measured_from:" \
    "gnucash_revaluation, while the Hong Kong dollars — whose cost basis" \
    "does agree with what the account holds — are measured from theirs." \
    "" \
    "The way out is to state the borrowing in Canadian dollars, at the rate" \
    "of the day. Then every dollar in the book has a cost behind it and the" \
    "whole currency is measured from its own cost bases." \
    "" \
    "fx-balances --verify-costs finds nothing here, and there is nothing to" \
    "find: no cost basis has moved without a sale. What it cannot tell you" \
    "is that a currency arrived uncosted, which is what measured_from on the" \
    "balance sheet is for." \
    "" \
    "The page opens with a warning, because the book keeps Expenses:Interest" \
    "in US dollars — which gnucash-plaintext does not support."

# --- Bought US-listed shares and still holds them ---------------------------
B="$BOOKS/shares.gnucash"
gp import --new "$B" "$F/a_cad_book_holding_us_listed_shares.txt" > /dev/null
settle "$B"
write_example "$B" 2026-12-31 \
    us_listed_shares_bought_and_still_held.txt \
    "A Canadian company that bought US-listed shares and still holds them" \
    "12 NASDAQ:AMZN bought at 200.00 USD with the US dollar at 1.30, so" \
    "3,120.00 CAD left the bank — 260.00 CAD a share. Still held at the year" \
    "end, with the share at 280.00 USD and the dollar at 1.42." \
    "" \
    "The shares open a cost basis of their own, in the book's own currency," \
    "at the 260.00 a share they cost. This book holds no foreign currency at" \
    "all, so the page states the whole gain under unrealized_gains_other" \
    "with unrealized_gains_fx at 0.00."

# --- A US loan recorded in Canadian dollars, settled with earned dollars ----
B="$BOOKS/cadloan.gnucash"
gp import --new "$B" \
    "$F/a_cad_book_recording_a_us_loan_as_a_canadian_liability.txt" > /dev/null
settle "$B"
g=$(gp fx-balances "$B" | grep 'USD Bank' | grep -oE '[0-9a-f]{32}' | head -1)
sed "s/{usd_basis}/$g/" "$F/the_us_loan_repaid_with_earned_us_dollars.txt" \
    > "$BOOKS/repay.txt"
gp import "$B" "$BOOKS/repay.txt" > /dev/null
settle "$B"
write_example "$B" 2026-12-31 \
    a_us_loan_recorded_in_canadian_dollars.txt \
    "A Canadian company that records a US dollar loan in Canadian dollars" \
    "100.00 USD borrowed and written into the book as 130.00 CAD owed, then" \
    "settled with 100.00 USD the company earned when the dollar was 1.40." \
    "" \
    "A liability held in the book's own currency holds no foreign currency," \
    "so it opens no cost basis, and while the loan stands the sheet states" \
    "nothing about the exposure at all: every gain key reads 0.00 while" \
    "130.00 CAD sits in the liabilities. Drawn as of 2026-11-30, the day" \
    "before the repayment, that is what it says." \
    "" \
    "The exposure arrives in one entry, on the day the debt is settled. The" \
    "dollars did not have to be bought: a company invoicing US customers" \
    "earns them, and what it earns carries a cost basis like anything else." \
    "Disposed of at what they cost — 140.00 CAD — against a debt carried at" \
    "130.00, they realize a loss of 10.00, and the working shows the entry" \
    "it came from."

echo
echo "Done. $(find "$OUT" -name '*.txt' | wc -l) examples in $OUT/"
